### ISSUE TITLE
Write GetSpeakers method in dbOpeations.cs

### ISSUE THREAD

**Issue by johnpankowicz** [govmeeting/govmeeting#14]
This method will execute a query to read a list of speakers at a specific meeting from the database.

**Comment by johnpankowicz** [comment]
This issue was made into a "Todo" comment within the source code. It is just unfinished code that needs to be completed.

**Comment by johnpankowicz** [comment]
This issue was made into a "Todo" comment within the source code. It is just unfinished code that needs to be completed.

**Comment by jjonas3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Database organization/ ORM organization](https://trello.com/c/dufzZ5ku/5-database-organization-orm-organization)
