### ISSUE TITLE
beta release

### ISSUE THREAD

**Issue by johnpankowicz** [govmeeting/govmeeting#95]
There are many advantages to having an actual release of the software, which people can start using as soon as possible. This release can have a minimum subset of the features of the eventual full system.
We can choose a few local small towns that already have online recordings of their meetings. We can approach them and ask if they would want to use the software, and serve as a test site.

The subset of features would include:
* Retrieving the most recent recording as soon as it becomes available.
* Transcribing the meeting.
* Providing a viewable and easy navigable transcript.
* Providing an edit screen for correcting text and speaker names.
* Providing registration and login.
* Perform authorization for viewing vs editing of transcripts.

There are towns and cities that already try to do this today, using commercial transcription software. We can provide advantages over how it is done today, by also doing the following:

* Automatically retrieve recordings and do the transcription, as opposed to some of the manual steps used today.
* Increaae the accuracy of the transcription by using common town government phrases and names of officers in the hints to the transcription.
* Automatically assign the correct speaker names for town officers.
* Allow either a town employee or a town volunteer to perform the editing since they won’t need access to the town’s computer system.

As more of the software is completed, we can release additional features.

**Comment by jjonas3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set-up Beta](https://trello.com/c/n1m7TGX8/4-set-up-beta)

**Comment by johnpankowicz** [comment]
This issue is duplicated by #135
